[package]
name = "husako-sdk"
version = "0.1.0"
edition.workspace = true
description = "Builtin JS runtime sources and base type definitions for husako"
license.workspace = true
repository.workspace = true

[dependencies]
