[package]
name = "husako-zed"
version = "0.1.0"
edition = "2021"
description = "Zed extension for husako .husako files"
license = "MIT"
repository = "https://github.com/nanazt/husako"

[lib]
crate-type = ["cdylib"]
path = "src/husako.rs"

[dependencies]
zed_extension_api = "0.1"
