[resources]
k8s = { source = "release", version = "1.35" }

[charts]
# redis = { source = "artifacthub", package = "bitnami/redis", version = "25.3.0" }
# postgresql = { source = "artifacthub", package = "bitnami/postgresql", version = "18.4.0" }
# metallb = { source = "artifacthub", package = "metallb/metallb", version = "0.15.3" }
