[package]
name = "husako-yaml"
version.workspace = true
edition.workspace = true
description = "JSON to YAML/JSON emitter for husako"
license.workspace = true
repository.workspace = true

[dependencies]
serde_json.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true
