[package]
name = "husako-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
husako-compile-oxc = { path = "../husako-compile-oxc" }
husako-dts = { path = "../husako-dts" }
husako-openapi = { path = "../husako-openapi" }
husako-runtime-qjs = { path = "../husako-runtime-qjs" }
husako-sdk = { path = "../husako-sdk" }
husako-yaml = { path = "../husako-yaml" }
regex-lite = "0.1"
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
