[entries]
dev = "dev/main.ts"
staging = "staging/main.ts"
release = "release/main.ts"

[resources]
kubernetes = { source = "release", version = "1.35" }

# [charts]
# ingress-nginx = { source = "registry", repo = "https://kubernetes.github.io/ingress-nginx", chart = "ingress-nginx", version = "4.12.0" }
